### PR TITLE
Revert "separate nhw-enc from library, add unified quality option"

### PR DESCRIPTION
**Pull request by rcanut**

### CODE REVIEW

**Comment by tansy** [comment]
What was wrong with that?

**Comment by rcanut** [comment]
Hi tansy,

Actually I compiled with: gcc *.c -O3 -o nhw-enc, and at the same quality setting, .nhw file size is different (from previous version) and decoded images are also different.I would like that .nhw file size and decoded image to be the same as the previous version.

Many thanks again.
Cheers,
Raphael

**Comment by tansy** [comment]
I didn't change codec in any way. It's just different client user interface

I just checked and the files are different. I don't get why add I just remapped low20-low1-norm-high1-high3 into 1-24.
I must have missed something.

**Comment by rcanut** [comment]
Yes, I totally agree with you.I am missing something too.

**Pull request merged**
